// This file contains API specifications for the Neoterik HTTP service.

### Register User Command
POST http://localhost:8000/register-user
Content-Type: application/json

{
  "id": "a86c2369-4f05-46f7-a186-48390b4f149d",
  "email": "paragpurandare50@gmail.com",        
  "name": "Parag Purandare",                    
  "avatar_url": "", 
  "github_username": "paragpurandare" 
}

### Upload Resume Command
POST http://localhost:8000/upload-resume
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="user_id"

a86c2369-4f05-46f7-a186-48390b4f149d
--boundary
Content-Disposition: form-data; name="file"; filename="resume.pdf"
Content-Type: application/pdf

< ./api/sample_resume/parag_cv.pdf
--boundary--


### Submit GitHub Username Command
POST http://localhost:8000/submit-github
Content-Type: application/x-www-form-urlencoded

user_id=a86c2369-4f05-46f7-a186-48390b4f149d&github_username=paragpurandare


### Generate cover letter command

POST http://localhost:8000/generate-cover-letter
Content-Type: application/json

{
  "user_id": "a86c2369-4f05-46f7-a186-48390b4f149d",         
  "job_title": "Software Engineer",       
  "hiring_company": "Acme Corp",        
  "job_description": "We are looking for a Software Engineer...", 
  "preferred_qualifications": "Python, FastAPI, SQL",            
  "company_culture_notes": "We value innovation and teamwork.",     
  "applicant_name": "Parag Purandare",      
  "desired_tone": "professional"           
}


### Check URL command

POST http://localhost:8000/check-url
Content-Type: application/json

{
    "url": "https://job-boards.greenhouse.io/layerzerolabs/jobs/5554606004?source=web3.career&gh_src=web3.career#application_form"
}

// run-agent command to scrap job info
POST http://localhost:8000/run-agent
Content-Type: application/json

{
    "url": "https://job-boards.greenhouse.io/layerzerolabs/jobs/5554606004?source=web3.career&gh_src=web3.career#application_form"
}

